name: Playwright Tests

on:
    push:
        branches:
            - main  # Or your main branch
    pull_request:
        branches:
            - main
    schedule:
       - cron: "0 9,5 * * 1-5"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
           - name: checkout the code
             uses: actions/checkout@v3
           - name: say Hello
             run: echo "Hello Playwright"
              

        
