name: Playwright Tests

on:
  push:
    branches:
      - main  # Or your main branch (e.g., "master")
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]  # Test with different Node.js versions if needed
        module: [module1, module2] # Define modules here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies (${{ matrix.module }})
        working-directory: ${{ matrix.module }}
        run: npm ci # Or yarn install

      - name: Install Playwright Browsers (${{ matrix.module }})
        working-directory: ${{ matrix.module }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests (${{ matrix.module }})
        working-directory: ${{ matrix.module }}
        run: npx playwright test

      - name: Upload Playwright Report (${{ matrix.module }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.module }}-${{ matrix.node-version }}
          path: ${{ matrix.module }}/playwright-report/
          retention-days: 10


